defaults: &defaults
  secret_token: '0c1d9a3ad87e4de81c7f6f60f617ba6880666fb4e50925574f2f10d15a9f9df918b91d8b1488edf038f1877c4a870e62a2cc02749ba063e1e11806778cb525af'
  mailgun:
    address: "smtp.mailgun.org"
    port: 587
    domain: "redstonelabs.mailgun.org"
    user_name: "postmaster@redstonelabs.mailgun.org"
    password: ""
  airbrake:
    api_key: ""
  omniauth:
    github:
      key: "927a0bef13ad23c58248"
      secret: "8e5e044e3b37ddbb425c725d001b489e7ec28845"
  resque:
    http_username: gistflow
    http_password: gistflow
  http_auth:
    username: Gistflow
    password: Gistflow
  rackspace:
    username: gistflow
    api_key: gistflow
  private_key_salt: asfdlaiw73byia7wv5coaw837cbawu
  google_analytics:
    login: ""
    password: ""
    web_property_id: ""
development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults